name: Bug report
description: Something went wrong
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Troubleshooting docs
      description: Please check the [troubleshooting docs](https://mamba.readthedocs.io/en/latest/user_guide/troubleshooting.html) before making a report.
      options:
        - label: "My problem is not solved in the Troubleshooting docs"
          required: true
  - type: input
    id: search
    attributes:
      label: Search tried in issue tracker
      description: Please search for similar issues before making a report.
      placeholder: ...
    validations:
      required: true
  - type: dropdown
    id: program
    attributes:
      label: Program
      description: What program(s) are you reporting this issue for?
      options:
        - Mamba
        - Microbamba
      multiple: true
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: mamba --version or micromamba --version
      placeholder: 0.27.0
    validations:
      required: true
  - type: textarea
    id: freeform
    attributes:
      label: Describe your issue
    validations:
      required: true
  - type: textarea
    id: environment_yml
    attributes:
      label: environment.yml
      description: If applicable; auto-rendered as YAML, no need for backticks
      placeholder: |
        channels: ...
        dependencies: ...
      render: yaml
  - type: textarea
    id: condarc
    attributes:
      label: ~/.condarc
      description: '`cat ~/.condarc`; auto-rendered as YAML, no need for backticks'
      placeholder: 'dependencies: ...'
      render: yaml
