on:
  push: null
  pull_request: null

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: windows-latest
    steps:
      - run: |
          which python
          python -VV
          echo 1337
        shell: cmd /C call {0}
        if: true
      - run: echo 42
        shell: cmd /C call {0}
