
name: Test micro.mamba.pm

on:
  schedule:
    - cron: '* * * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

defaults:
  run:
    shell: bash -el {0}

jobs:
  test_micro_mamba_pm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Install Micromamba (${{ matrix.os }}, ${{ matrix.shell }})
        run: |
          curl -v ifconfig.me
