on:
  push: null
  pull_request: null

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: windows-latest
    steps:
      - run: |
          bash -c 'exit 1'
          echo 1337
        shell: cmd /C call {0}
      - run: echo 42
        shell: cmd /C call {0}
